Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node5: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 975, in getMetrics
    skew_Wnotheta = fitSkew(x,Wnotheta_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node5: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 975, in getMetrics
    skew_Wnotheta = fitSkew(x,Wnotheta_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node5: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node7: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node7: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node1: task 0: Exited with exit code 1
/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py:828: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 975, in getMetrics
    skew_Wnotheta = fitSkew(x,Wnotheta_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node1: task 0: Exited with exit code 1
srun: error: enc1-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 87, in <module>
    R_w, R_nw, SNR_w, SNR_nw, skew_w, skew_nw, skew_m = agent.getMetrics(time=30)
  File "../../mazeAgentUtils.py", line 975, in getMetrics
    skew_Wnotheta = fitSkew(x,Wnotheta_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 87, in <module>
    R_w, R_nw, SNR_w, SNR_nw, skew_w, skew_nw, skew_m = agent.getMetrics(time=30)
  File "../../mazeAgentUtils.py", line 975, in getMetrics
    skew_Wnotheta = fitSkew(x,Wnotheta_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 87, in <module>
    R_w, R_nw, SNR_w, SNR_nw, skew_w, skew_nw, skew_m = agent.getMetrics(time=30)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 87, in <module>
    R_w, R_nw, SNR_w, SNR_nw, skew_w, skew_nw, skew_m = agent.getMetrics(time=30)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc1-node3: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node5: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 87, in <module>
    R_w, R_nw, SNR_w, SNR_nw, skew_w, skew_nw, skew_m = agent.getMetrics(time=30)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node6: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 87, in <module>
    R_w, R_nw, SNR_w, SNR_nw, skew_w, skew_nw, skew_m = agent.getMetrics(time=30)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node5: task 0: Exited with exit code 1
srun: error: enc0-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 975, in getMetrics
    skew_Wnotheta = fitSkew(x,Wnotheta_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node2: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node4: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 975, in getMetrics
    skew_Wnotheta = fitSkew(x,Wnotheta_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 87, in <module>
    R_w, R_nw, SNR_w, SNR_nw, skew_w, skew_nw, skew_m = agent.getMetrics(time=30)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node2: task 0: Exited with exit code 1
srun: error: enc0-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node1: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "clusterSweep.py", line 84, in <module>
    fig1, ax1 = plotter.plotVarianceAndError()
  File "../../mazeAgentUtils.py", line 1609, in plotVarianceAndError
    R2_W, R2_Wnotheta, SNR_W, SNR_Wnotheta, skew_W, skew_Wnotheta, skew_M = self.mazeAgent.getMetrics(time=time)
  File "../../mazeAgentUtils.py", line 974, in getMetrics
    skew_W = fitSkew(x,W_flat)
  File "../../mazeAgentUtils.py", line 1868, in fitSkew
    (a,loc,scale), _ = scipy.optimize.curve_fit(skewnorm,x,y,maxfev=5000)
  File "/nfs/nhome/live/tgeorge/anaconda3/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 789, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 5000.
srun: error: enc0-node1: task 0: Exited with exit code 1
