../mazeAgentUtils.py:1538: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "tight_layout" which is no longer supported as of 3.3 and will become an error two minor releases later
  fig.savefig(path+".pdf", dpi=400,tight_layout=tight_layout,transparent=transparent)
../mazeAgentUtils.py:1538: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "tight_layout" which is no longer supported as of 3.3 and will become an error two minor releases later
  fig.savefig(path+".pdf", dpi=400,tight_layout=tight_layout,transparent=transparent)
../mazeAgentUtils.py:1541: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "tight_layout" which is no longer supported as of 3.3 and will become an error two minor releases later
  fig.savefig(specialLocation, dpi=400,tight_layout=False,transparent=transparent)
../mazeAgentUtils.py:1538: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "tight_layout" which is no longer supported as of 3.3 and will become an error two minor releases later
  fig.savefig(path+".pdf", dpi=400,tight_layout=tight_layout,transparent=transparent)
../mazeAgentUtils.py:1538: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "tight_layout" which is no longer supported as of 3.3 and will become an error two minor releases later
  fig.savefig(path+".pdf", dpi=400,tight_layout=tight_layout,transparent=transparent)
../mazeAgentUtils.py:1541: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "tight_layout" which is no longer supported as of 3.3 and will become an error two minor releases later
  fig.savefig(specialLocation, dpi=400,tight_layout=False,transparent=transparent)
Traceback (most recent call last):
  File "clusterSweep.py", line 59, in <module>
    sys.stdout.flush()
OSError: [Errno 116] Stale file handle
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [Errno 116] Stale file handle
../mazeAgentUtils.py:1538: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "tight_layout" which is no longer supported as of 3.3 and will become an error two minor releases later
  fig.savefig(path+".pdf", dpi=400,tight_layout=tight_layout,transparent=transparent)
../mazeAgentUtils.py:1538: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "tight_layout" which is no longer supported as of 3.3 and will become an error two minor releases later
  fig.savefig(path+".pdf", dpi=400,tight_layout=tight_layout,transparent=transparent)
../mazeAgentUtils.py:1541: MatplotlibDeprecationWarning: savefig() got unexpected keyword argument "tight_layout" which is no longer supported as of 3.3 and will become an error two minor releases later
  fig.savefig(specialLocation, dpi=400,tight_layout=False,transparent=transparent)
Traceback (most recent call last):
  File "clusterSweep.py", line 59, in <module>
    sys.stdout.flush()
OSError: [Errno 116] Stale file handle
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [Errno 116] Stale file handle
